"""Self-contained policy hook rendered for remote agent machines.

The remote hook deliberately does not import Engram or trust agent supplied
context.  It determines the repository and branch on the remote filesystem.
"""
from __future__ import annotations

import json
from typing import Final

REMOTE_POLICY_MARKER: Final = "engram-remote-agent-policy-hook-v1"
REMOTE_POLICY_PROVIDERS: Final = ("claude-code", "codex", "antigravity")


def remote_policy_hook_relpath(provider: str, remote_os: str) -> str:
    safe = provider.replace("-code", "")
    return f".engram/{REMOTE_POLICY_MARKER}-{safe}.py"


def remote_policy_hook_command(provider: str, path: str, remote_os: str) -> str:
    executable = "python" if remote_os == "windows" else "python3"
    return f'{executable} "{path}" --provider {provider}'


def render_remote_policy_hook(provider: str, *, remote_os: str = "posix") -> str:
    """Return a dependency-free remote classifier executable.

    Provisioning already selects a remote Python interpreter on both POSIX and
    Windows, so the same portable standard-library script is deployed to both.
    """
    if provider not in REMOTE_POLICY_PROVIDERS:
        raise ValueError(f"unsupported provider {provider!r}")
    # This code has no project imports. Unknown shell commands are only allowed
    # on a resolved non-protected branch; protected/detached contexts fail
    # closed unless the command is confidently read-only.
    return fr'''#!/usr/bin/env python3
# {REMOTE_POLICY_MARKER}; generated by Engram. Do not edit.
import json, os, re, shlex, subprocess, sys
PROVIDER = {provider!r}
PROTECTED = {{"main", "master", "dev"}}
MUTATING_TOOLS = {{"write", "write_file", "edit", "apply_patch", "replace", "delete", "write_to_file", "replace_file_content", "multi_replace_file_content"}}
GIT_MUTATIONS = {{"commit", "merge", "rebase", "reset", "checkout", "switch", "cherry-pick", "revert", "worktree", "clone", "push", "branch", "tag"}}
READ_ONLY = {{"cat", "ls", "pwd", "rg", "grep", "find", "git", "head", "tail", "echo"}}
def text(v): return v if isinstance(v, str) else ""
def payload(raw):
    try: return json.loads(raw)
    except Exception: return {{}}
def extract(p):
    tc = p.get("toolCall") if isinstance(p.get("toolCall"), dict) else {{}}
    name = text(tc.get("name") or p.get("tool_name") or p.get("toolName")).lower()
    args = tc.get("args") if isinstance(tc.get("args"), dict) else (p.get("tool_input") if isinstance(p.get("tool_input"), dict) else {{}})
    cwd = text(args.get("Cwd") or args.get("cwd") or p.get("cwd") or p.get("working_directory"))
    command = text(args.get("CommandLine") or args.get("command") or args.get("cmd"))
    return name, args, cwd, command
def target_path(args, cwd):
    for key in ("file_path", "path", "TargetFile", "target_file", "PatchFile", "patch_file"):
        value=text(args.get(key))
        if value: return value if os.path.isabs(value) else os.path.join(cwd, value)
    patch=text(args.get("patch") or args.get("Patch"))
    m=re.search(r"\*\*\*\s+(?:Add|Update|Delete)\s+File:\s*([^\r\n]+)", patch)
    if m:
        value=m.group(1).strip()
        return value if os.path.isabs(value) else os.path.normpath(os.path.join(cwd, value))
    m=re.search(r"(?:\+\+\+|---)\s+(?:[ab]/)?([^\s]+)", patch)
    if m: return os.path.join(cwd, m.group(1))
    return cwd
def command_target(command, cwd):
    try: tokens=shlex.split(command, posix=os.name != "nt")
    except Exception: return cwd
    for i, token in enumerate(tokens):
        if os.path.basename(token).lower() in ("git", "git.exe"):
            j=i+1
            while j < len(tokens):
                if tokens[j] == "-C" and j+1 < len(tokens):
                    value=tokens[j+1]; return value if os.path.isabs(value) else os.path.join(cwd, value)
                if tokens[j].startswith("-C") and len(tokens[j]) > 2:
                    value=tokens[j][2:]; return value if os.path.isabs(value) else os.path.join(cwd, value)
                j+=1
    return cwd
def branch(path):
    if not path: return ""
    probe=path if os.path.isdir(path) else os.path.dirname(path)
    try:
        root=subprocess.check_output(["git", "-C", probe, "rev-parse", "--show-toplevel"], stderr=subprocess.DEVNULL, text=True).strip()
        return subprocess.check_output(["git", "-C", root, "symbolic-ref", "--quiet", "--short", "HEAD"], stderr=subprocess.DEVNULL, text=True).strip()
    except Exception: return ""
def shell_readonly(command):
    # Pipelines/control operators can hide a writer after an innocent first
    # command (including PowerShell Set-Content), so protected contexts never
    # attempt to prove them read-only.
    if not command or re.search(r"(?:>>?|[|;&]|\r|\n|\$\(|`)", command): return False
    try: tokens=shlex.split(command, posix=os.name != "nt")
    except Exception: return False
    if not tokens: return True
    first=os.path.basename(tokens[0]).lower()
    if first not in READ_ONLY: return False
    if first == "git":
        words=[x.lower() for x in tokens[1:] if not x.startswith("-")]
        return bool(words) and words[-1] in {{"status", "log", "diff", "show", "rev-parse", "branch"}}
    return True
def shell_mutates(command):
    if not shell_readonly(command): return True
    try: tokens=[x.lower() for x in shlex.split(command, posix=os.name != "nt")]
    except Exception: return True
    return any(t in GIT_MUTATIONS for t in tokens) or any(t in {{"rm", "del", "move", "mv", "cp", "copy", "sed", "tee", "apply_patch"}} for t in tokens)
def main():
    p=payload(sys.stdin.read()); name,args,cwd,command=extract(p); deny=False; reason=""
    shell=name in ("run_command", "bash", "shell", "command", "execute")
    direct=name in MUTATING_TOOLS
    is_mutation=direct or (shell and shell_mutates(command))
    target=target_path(args, cwd) if direct else (command_target(command, cwd) if shell else cwd)
    b=branch(target)
    if is_mutation and (not b or b in PROTECTED):
        deny=True; reason=("mutation denied: remote git branch is detached or unresolved" if not b else "mutation denied on protected branch " + b)
    elif shell and not shell_readonly(command) and (not b or b in PROTECTED):
        deny=True; reason=("shell command denied: remote git branch is detached or unresolved" if not b else "shell command denied on protected branch " + b)
    if PROVIDER == "antigravity":
        out={{"decision": "deny" if deny else "allow"}}
        if reason: out["reason"]=reason
    elif deny:
        out={{"hookSpecificOutput":{{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":reason}}}}
    else: out={{}}
    sys.stdout.write(json.dumps(out,separators=(",",":")))
if __name__ == "__main__": main()
'''


def policy_payload(remote_os: str) -> dict[str, dict[str, str]]:
    if remote_os not in {"posix", "windows"}:
        raise ValueError(f"unsupported remote_os {remote_os!r}")
    result: dict[str, dict[str, str]] = {}
    for provider in REMOTE_POLICY_PROVIDERS:
        relpath = remote_policy_hook_relpath(provider, remote_os)
        result[provider] = {
            "marker": REMOTE_POLICY_MARKER,
            "relpath": relpath,
            "command": remote_policy_hook_command(provider, relpath, remote_os),
            "body": render_remote_policy_hook(provider, remote_os=remote_os),
        }
    return result
